# Generated by Django 4.2.4 on 2023-11-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='track_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Трэк №'),
        ),
    ]
