# Generated by Django 4.2.4 on 2023-10-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Поступил'), (2, 'Собран'), (3, 'Отправлен'), (4, 'Срочно')], default=1),
        ),
    ]
